### ISSUE TITLE
sneaker download to STDOUT prints information other than the secret

### ISSUE THREAD

**Issue by fwisehc** [codahale/sneaker#14]
I would think that the following would only output the secret to STDOUT and not the downloading status message.

**Expected Behavior**
```
% sneaker download my-secret -
this-is-the-secret                                                                                                                  
```

**Current Behavior**
Instead it prints a downloading status and then prints the secret.
```
% sneaker download my-secret -
2016/04/28 15:29:58 downloading -
this-is-the-secret
```

The documentation says:
```
Likewise, using - as the output path will make sneaker write the data to STDOUT. 
This allows you to pipe the output directly to a tar process, for example.
```

**Comment by darrin-wortlehock** [comment]
The messages are printed to stderr, only the output is sent to stdout.  Your console shows you both stdout and stderr.
