### ISSUE TITLE
Github Releases?

### ISSUE THREAD

**Issue by wolfeidau** [codahale/sneaker#9]
It would be nice to get release binaries via github, would you be interested in a pull request to add some release logic to the makefile?

In a similar way to how I have done it here https://github.com/wolfeidau/coffer/blob/master/Makefile.

Any other suggestions on how I could help with distribution of binaries are of course welcome.

Cheers

**Comment by codahale** [comment]
I would prefer to not be in the business of providing binaries, honestly. Git's content-addressability gives some degree of guarantee of integrity for free; to securely host binaries I'd have to spin up a GPG keypair and that'd be a hassle.
